olevba 0.60.1.dev3 on Python 3.8.10 - http://decalage.info/python/oletools
===============================================================================
FILE: Trojan-Dropper.MSExcel.Agent.w-a9fb8ff6cb4c7ab2e8fb9b785eac47524a96937e
Type: OLE
-------------------------------------------------------------------------------
VBA MACRO ThisWorkbook 
in file: Trojan-Dropper.MSExcel.Agent.w-a9fb8ff6cb4c7ab2e8fb9b785eac47524a96937e - OLE stream: 'ThisWorkbook'
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
(empty macro)
-------------------------------------------------------------------------------
VBA MACRO Sheet1 
in file: Trojan-Dropper.MSExcel.Agent.w-a9fb8ff6cb4c7ab2e8fb9b785eac47524a96937e - OLE stream: 'Sheet1'
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
(empty macro)
+----------+--------------------+---------------------------------------------+
|Type      |Keyword             |Description                                  |
+----------+--------------------+---------------------------------------------+
|Suspicious|Hex Strings         |Hex-encoded strings were detected, may be    |
|          |                    |used to obfuscate strings (option --decode to|
|          |                    |see all)                                     |
+----------+--------------------+---------------------------------------------+

